name: 'publish npm'

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # required for npm provenance
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
          registry-url: https://registry.npmjs.org

      - name: ci
        run: npm ci

      - name: build:package
        run: npm run build:package

      - name: check:package
        run: npm run check:package

      - name: lint:check
        run: npm run lint:check

      - name: test:coverage
        run: npm run test:coverage

      - name: publish
        run: npm publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
